[package]
name = "rustcameratest"
version = "0.1.0"
edition = "2024"

[dependencies]
gpui = "0.2.2"

[dependencies.nokhwa]
version = "0.10"
# Use the native input backends, enable WGPU integration
features = ["input-native"]

# add this to enable exporting to a JPEG/PNG
[dependencies.image]
version = "0.25"
features = ["default-formats"]